name: Build Flutter APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.0'
        channel: 'stable'
        cache: true

    - name: Flutter Doctor
      run: flutter doctor -v

    - name: Clean Flutter
      run: flutter clean

    - name: Get dependencies
      run: flutter pub get

    - name: Build APK (Release)
      run: |
        echo "========== Starting APK build =========="
        flutter build apk --release --verbose --no-tree-shake-icons 2>&1 | tee build_log.txt
        BUILD_EXIT_CODE=${PIPESTATUS[0]}
        echo "Build exit code: $BUILD_EXIT_CODE"

        echo "========== Checking build directory =========="
        ls -R build/ || echo "Build directory not found"

        if [ $BUILD_EXIT_CODE -ne 0 ]; then
          echo "Build failed with exit code $BUILD_EXIT_CODE"
          cat build_log.txt
          exit $BUILD_EXIT_CODE
        fi

    - name: Verify APK exists
      run: |
        echo "========== Verifying APK =========="
        find build -name "*.apk" -type f || echo "No APK files found anywhere"

        if [ -d "build/app/outputs/flutter-apk/" ]; then
          ls -lah build/app/outputs/flutter-apk/
        else
          echo "ERROR: flutter-apk directory does not exist!"
          exit 1
        fi

    - name: Upload Release APK
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: virtual-glasses-apk
        path: build/app/outputs/flutter-apk/*.apk
        retention-days: 30
        if-no-files-found: error
