name: Build Flutter APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.0'
        channel: 'stable'
        cache: true

    - name: Flutter Doctor
      run: flutter doctor -v

    - name: Clean Flutter
      run: flutter clean

    - name: Get dependencies
      run: flutter pub get

    - name: Check for Flutter errors
      run: |
        echo "========== Running Flutter analyze =========="
        flutter analyze || true

    - name: Build APK (Release)
      run: |
        echo "========== Starting APK build =========="
        flutter build apk --release --verbose 2>&1 | tee build.log
        exit ${PIPESTATUS[0]}

    - name: Find APK files
      run: |
        echo "========== Searching for APK files =========="
        find . -name "*.apk" -type f
        ls -R build/app/outputs/ || true

    - name: Upload Release APKs
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: virtual-glasses-apk
        path: |
          build/app/outputs/flutter-apk/*.apk
          build/app/outputs/apk/release/*.apk
        retention-days: 30
        if-no-files-found: warn
